CREATE DATABASE InLock_Games_Manha

USE InLock_Games_Manha

CREATE TABLE ESTUDIOS (
	EstudioId INT IDENTITY PRIMARY KEY
	, NomeEstudio VARCHAR(250) NOT NULL
);

CREATE TABLE JOGOS (
	JogoId INT IDENTITY PRIMARY KEY
	, NomeJogo VARCHAR(250) NOT NULL UNIQUE
	, Descricao TEXT NOT NULL
	, DataLancamento DATE NOT NULL 
	, Valor MONEY NOT NULL
	, EstudioId INT FOREIGN KEY REFERENCES ESTUDIOS(EstudioId)
);

CREATE TABLE USUARIOS (
	UsuarioId INT IDENTITY PRIMARY KEY
	, Email VARCHAR (250) NOT NULL UNIQUE
	, Senha VARCHAR (100) NOT NULL
	, TipoUsuario VARCHAR(50) NOT NULL
);